import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import LeftSideBar from '@/components/layout/LeftSideBar';
import MainContainer from '@/components/layout/MainContainer';
import RightSideBar from '@/components/layout/RightSideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} `}>
                    <main className="flex flex-row font-roboto h-[200vh]">
                        <LeftSideBar />
                        <MainContainer>{children}</MainContainer>
                        <RightSideBar />
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
